spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation : true
server:
  port: 8080

